######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 9 20:40:50 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += window.ui
HEADERS += ui_window.h \
    mainwindow.h

SOURCES += \
    mainwindow.cpp \
    main.cpp
